const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,DPR=devicePixelRatio||1;
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();

const $=id=>document.getElementById(id),keys={};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.key.toLowerCase()==='p'&&state==='play')togglePause()});
addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;keys[e.code]=false});

const pilots=[
{name:'NOVA',role:'BALANCED',color:'#22d3ee',speed:275,hp:100,fire:.19,damage:18,desc:'Balanced rift runner'},
{name:'BYTE',role:'TECH',color:'#a855f7',speed:245,hp:120,fire:.23,damage:22,desc:'Heavy shield specialist'},
{name:'FLUX',role:'SPEED',color:'#f472b6',speed:330,hp:82,fire:.14,damage:14,desc:'Extreme mobility pilot'},
{name:'ECHO',role:'POWER',color:'#fbbf24',speed:225,hp:105,fire:.31,damage:34,desc:'High-impact energy shots'}
];
const dimensions=[
{name:'NEON CITY',accent:'#22d3ee',bg1:'#040713',bg2:'#101044',hazard:'CYBER SWARM'},
{name:'CRYSTAL VOID',accent:'#a855f7',bg1:'#090316',bg2:'#31105a',hazard:'PRISM BROOD'},
{name:'CYBER JUNGLE',accent:'#34d399',bg1:'#02110e',bg2:'#123b2f',hazard:'BIO MACHINES'},
{name:'SOLAR GRAVE',accent:'#fb7185',bg1:'#170505',bg2:'#4b1620',hazard:'FIRE HIVE'},
{name:'THE RIFT',accent:'#60a5fa',bg1:'#030318',bg2:'#1b1760',hazard:'VOID ENTITY'}
];
const difficulty={cadet:{hp:.82,dmg:.72,spawn:.82,label:'CADET'},normal:{hp:1,dmg:1,spawn:1,label:'NORMAL'},rift:{hp:1.38,dmg:1.34,spawn:1.24,label:'RIFT'}};
const config={players:1,p1:0,p2:1,dimension:0,startLevel:1,difficulty:'normal',music:65,sfx:75};
let state='menu',paused=false,last=performance.now(),distance=0,score=0,kills=0,level=1,dimIndex=0,scrollSpeed=175,spawnTimer=0,powerTimer=6,portalAt=850,portalSegmentStart=0,portal=null,boss=null,bossSpawnedLevel=0,shake=0;
let ships=[],aliens=[],shots=[],enemyShots=[],particles=[],powerItems=[],stars=[],nebulae=[];
for(let i=0;i<150;i++)stars.push({x:Math.random()*W,y:Math.random()*H,z:.2+Math.random()*.8,s:.5+Math.random()*1.8});
for(let i=0;i<10;i++)nebulae.push({x:Math.random()*W,y:Math.random()*H,r:90+Math.random()*180,a:.02+Math.random()*.05});

function buildMenu(){
 const renderChars=(id,player)=>{$(id).innerHTML=pilots.map((p,i)=>`<button class="character-card ${config[player]===i?'active':''}" style="--char:${p.color}" data-player="${player}" data-index="${i}"><div class="portrait"></div><b>${p.name}</b><small>${p.role}</small><p>${p.desc}</p></button>`).join('')};
 renderChars('p1Characters','p1');renderChars('p2Characters','p2');
 $('dimensionGrid').innerHTML=dimensions.map((d,i)=>`<button class="dimension-card ${config.dimension===i?'active':''}" data-dim="${i}" style="--accent:${d.accent};--d1:${d.bg1};--d2:${d.bg2}"><b>${d.name}</b><small>${d.hazard}</small></button>`).join('');
 document.querySelectorAll('.character-card').forEach(b=>b.onclick=()=>{config[b.dataset.player]=+b.dataset.index;buildMenu();updateLaunchSummary()});
 document.querySelectorAll('.dimension-card').forEach(b=>b.onclick=()=>{config.dimension=+b.dataset.dim;buildMenu();updateLaunchSummary()});
}
function updateLaunchSummary(){$('launchSummary').textContent=`${pilots[config.p1].name} · ${dimensions[config.dimension].name} · ${difficulty[config.difficulty].label}`}
buildMenu();updateLaunchSummary();
document.querySelectorAll('.mode-btn').forEach(b=>b.onclick=()=>{config.players=+b.dataset.mode;document.querySelectorAll('.mode-btn').forEach(x=>x.classList.toggle('active',x===b));$('p2Wrap').classList.toggle('hidden',config.players===1)});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')});
document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{config.difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('active',x===b));updateLaunchSummary()});
$('levelRange').oninput=e=>{config.startLevel=+e.target.value;$('levelValue').textContent=config.startLevel};
$('musicVolume').oninput=e=>{config.music=+e.target.value;$('musicValue').textContent=config.music+'%';audio.setMusic(config.music/100)};
$('sfxVolume').oninput=e=>{config.sfx=+e.target.value;$('sfxValue').textContent=config.sfx+'%'};

const audio={ctx:null,master:null,musicGain:null,enabled:true,timer:null,step:0,drones:[],
 init(){if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.musicGain=this.ctx.createGain();this.master.gain.value=.7;this.musicGain.gain.value=config.music/100*.45;this.musicGain.connect(this.master);this.master.connect(this.ctx.destination);this.startDrones();this.timer=setInterval(()=>this.tick(),330)},
 resume(){this.init();if(this.ctx.state==='suspended')this.ctx.resume()},
 setMusic(v){if(this.musicGain)this.musicGain.gain.setTargetAtTime(this.enabled?v*.45:0,this.ctx.currentTime,.08)},
 toggle(){this.enabled=!this.enabled;this.resume();this.setMusic(config.music/100);$('musicToggle').textContent=this.enabled?'♫ MUSIC ON':'♫ MUSIC OFF'},
 startDrones(){const now=this.ctx.currentTime;[55,82.41,110].forEach((f,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type=i===1?'triangle':'sine';o.frequency.value=f;filter.type='lowpass';filter.frequency.value=420;g.gain.value=[.04,.025,.018][i];o.connect(filter);filter.connect(g);g.connect(this.musicGain);o.start(now);this.drones.push(o)})},
 tick(){if(!this.ctx||!this.enabled)return;const scale=[220,246.94,293.66,329.63,369.99,440,493.88,587.33],intensity=state==='play'?(1+Math.min(level,20)*.008):.5,f=scale[this.step%scale.length]*intensity;this.note(f,.18,.05,'sine');if(this.step%4===0)this.note(f/2,.65,.034,'triangle');if(this.step%8===6)this.note(f*1.5,.12,.025,'sine');this.step++},
 note(freq,dur,vol,type='sine'){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain(),pan=this.ctx.createStereoPanner?this.ctx.createStereoPanner():null;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*.997,t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);if(pan){pan.pan.value=(Math.random()-.5)*.7;g.connect(pan);pan.connect(this.musicGain)}else g.connect(this.musicGain);o.start(t);o.stop(t+dur+.03)},
 sfx(freq=440,dur=.08,type='square',vol=.055){if(!this.ctx||config.sfx<=0)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.55),t+dur);g.gain.setValueAtTime(vol*(config.sfx/100),t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur)}};
$('musicToggle').onclick=()=>audio.toggle();

function makeShip(slot,pilotIndex){const p=pilots[pilotIndex];return{slot,pilot:p.name,color:p.color,x:slot===1?150:210,y:H*(slot===1?.45:.63),r:18,hp:p.hp,maxHp:p.hp,baseSpeed:p.speed,fireRate:p.fire,damage:p.damage,lastShot:0,pulse:100,alive:true,inv:0,speedMul:1,speedTimer:0,speedEffect:''}}
function resetGame(){level=config.startLevel;dimIndex=config.dimension;distance=(level-1)*850;portalSegmentStart=distance;portalAt=distance+850;score=0;kills=0;scrollSpeed=175+(level-1)*8.5;spawnTimer=.7;powerTimer=4+Math.random()*4;portal=null;boss=null;bossSpawnedLevel=0;shake=0;aliens=[];shots=[];enemyShots=[];particles=[];powerItems=[];ships=[makeShip(1,config.p1)];if(config.players===2)ships.push(makeShip(2,config.p2));updateHUD()}
function launch(){audio.resume();state='play';paused=false;$('menu').classList.add('hidden');$('gameOver').classList.add('hidden');$('pauseScreen').classList.add('hidden');$('hud').classList.remove('hidden');$('pauseBtn').classList.remove('hidden');resetGame();toast(`AUTO FIRE ONLINE // ${dimensions[dimIndex].name}`)}
$('launchBtn').onclick=launch;$('retryBtn').onclick=launch;
function toHangar(){state='menu';paused=false;$('menu').classList.remove('hidden');$('hud').classList.add('hidden');$('pauseScreen').classList.add('hidden');$('gameOver').classList.add('hidden');$('pauseBtn').classList.add('hidden');audio.setMusic(config.music/100)}
$('hangarBtn').onclick=toHangar;$('hangarBtn2').onclick=toHangar;
function togglePause(){if(state!=='play')return;paused=!paused;$('pauseScreen').classList.toggle('hidden',!paused)}
$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1500)}

function levelScale(){return{hp:1+(level-1)*.16,damage:1+(level-1)*.065,speed:1+(level-1)*.035,spawn:Math.max(.27,1.18-(level-1)*.055),shot:Math.max(.48,1-(level-1)*.028)}}
function spawnAlien(forceBoss=false){
 const diff=difficulty[config.difficulty],ls=levelScale();
 const types=[{name:'SKITTER',r:14,hp:34,speed:88,damage:10,color:'#7cf7ff',shoot:false},{name:'MANTA',r:22,hp:65,speed:68,damage:14,color:'#b56dff',shoot:true},{name:'EYE',r:17,hp:48,speed:64,damage:17,color:'#ff75bd',shoot:true},{name:'BRUTE',r:29,hp:128,speed:46,damage:23,color:'#ff946b',shoot:false},{name:'PHANTOM',r:20,hp:88,speed:92,damage:20,color:'#7df59d',shoot:true}];
 const unlocked=Math.min(types.length,2+Math.floor(level/2));
 const base=forceBoss?{name:'RIFT BEHEMOTH',r:52,hp:650,speed:32,damage:30,color:'#ff477e',shoot:true,boss:true}:types[Math.floor(Math.random()*unlocked)];
 const e={...base,x:W+70+Math.random()*120,y:105+Math.random()*Math.max(100,H-190),hp:base.hp*ls.hp*diff.hp,maxHp:base.hp*ls.hp*diff.hp,speed:base.speed*ls.speed,damage:base.damage*ls.damage*diff.dmg,lastShot:0,phase:Math.random()*Math.PI*2,dead:false};
 aliens.push(e);if(e.boss){boss=e;bossSpawnedLevel=level;toast(`⚠ LEVEL ${level} // RIFT BEHEMOTH`);audio.sfx(90,.5,'sawtooth',.1)}}
function spawnPowerItem(type){powerItems.push({type,x:W+70,y:120+Math.random()*Math.max(100,H-220),r:18,phase:Math.random()*6.2,life:14,color:type==='boost'?'#34d399':'#fb7185'})}

function nearestTarget(s){let best=null,bd=Infinity;for(const a of aliens){if(a.dead||a.x<s.x-20)continue;const d=(a.x-s.x)+Math.abs(a.y-s.y)*.55;if(d<bd){bd=d;best=a}}return best}
function shootShip(s,now){if(!s.alive||now-s.lastShot<s.fireRate*1000)return;s.lastShot=now;const target=nearestTarget(s);let ang=0;if(target)ang=Math.atan2(target.y-s.y,target.x-s.x);const speed=780+s.damage*2.2,damage=s.damage*(1+(level-1)*.035);shots.push({x:s.x+24,y:s.y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,r:4,damage,color:s.color,owner:s.slot,life:1.8});if(Math.random()<.45)audio.sfx(540+s.slot*95,.045,'square',.022)}
function pulseShip(s){if(!s.alive||s.pulse<100)return;s.pulse=0;shake=8;for(let i=0;i<42;i++)particle(s.x,s.y,s.color,7);aliens.forEach(a=>{const d=Math.hypot(a.x-s.x,a.y-s.y);if(d<350)a.hp-=85*(1-d/500)});enemyShots=enemyShots.filter(b=>Math.hypot(b.x-s.x,b.y-s.y)>330);audio.sfx(120,.55,'sawtooth',.12);toast(`${s.pilot} // RIFT PULSE`)}
let pulseLocks={g:false,ShiftRight:false};
function controls(s,dt,now){let dx=0,dy=0,pulseKey=false;if(s.slot===1){dx=(keys.d?1:0)-(keys.a?1:0);dy=(keys.s?1:0)-(keys.w?1:0);pulseKey=keys.g;if(pulseKey&&!pulseLocks.g){pulseShip(s);pulseLocks.g=true}if(!pulseKey)pulseLocks.g=false}else{dx=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);dy=(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0);pulseKey=keys.ShiftRight||keys.ShiftLeft;if(pulseKey&&!pulseLocks.ShiftRight){pulseShip(s);pulseLocks.ShiftRight=true}if(!pulseKey)pulseLocks.ShiftRight=false}const l=Math.hypot(dx,dy)||1,currentSpeed=s.baseSpeed*s.speedMul;s.x+=dx/l*currentSpeed*dt;s.y+=dy/l*currentSpeed*dt;s.x=Math.max(70,Math.min(W*.48,s.x));s.y=Math.max(95,Math.min(H-55,s.y));shootShip(s,now);s.inv=Math.max(0,s.inv-dt);s.pulse=Math.min(100,s.pulse+7*dt);if(s.speedTimer>0){s.speedTimer-=dt;if(s.speedTimer<=0){s.speedMul=1;s.speedEffect='';toast(`${s.pilot} // SPEED NORMALIZED`)}}}
function applyPowerItem(s,item){if(item.type==='boost'){s.speedMul=1.58;s.speedTimer=7;s.speedEffect='BOOST';score+=150;toast(`⚡ ${s.pilot} // SPEED BOOST +58%`);audio.sfx(760,.18,'sine',.08)}else{s.speedMul=.58;s.speedTimer=5;s.speedEffect='SLOW';toast(`▼ ${s.pilot} // SPEED DOWN -42%`);audio.sfx(150,.22,'sawtooth',.07)}for(let i=0;i<22;i++)particle(item.x,item.y,item.color,5)}

function enemyFire(a,now){if(!a.shoot)return;const ls=levelScale(),cooldown=(a.boss?680:1320)*ls.shot;if(now-a.lastShot<cooldown)return;a.lastShot=now;const live=ships.filter(s=>s.alive);if(!live.length)return;const t=live[Math.floor(Math.random()*live.length)],ang=Math.atan2(t.y-a.y,t.x-a.x),n=a.boss?Math.min(9,4+Math.floor(level/3)):1;for(let i=0;i<n;i++){const off=(i-(n-1)/2)*.11;enemyShots.push({x:a.x-a.r,y:a.y,vx:Math.cos(ang+off)*(a.boss?330:260),vy:Math.sin(ang+off)*(a.boss?330:260),r:a.boss?6:4,damage:a.damage,color:a.color,life:4})}}
function hurtShip(s,dmg){if(!s.alive||s.inv>0)return;s.hp-=dmg;s.inv=.5;shake=6;for(let i=0;i<12;i++)particle(s.x,s.y,'#fb7185',5);audio.sfx(105,.2,'sawtooth',.08);if(s.hp<=0)destroyShip(s)}
function destroyShip(s){s.hp=0;s.alive=false;for(let i=0;i<38;i++)particle(s.x,s.y,i%2?s.color:'#ffffff',8);audio.sfx(65,.6,'sawtooth',.12);toast(`${s.pilot} // SHIP DESTROYED`);if(!ships.some(x=>x.alive))endGame()}
function killAlien(a){a.dead=true;kills++;score+=a.boss?2500:100+level*12;shake=a.boss?12:3;for(let i=0;i<(a.boss?58:18);i++)particle(a.x,a.y,i%3===0?'#d8ff72':a.color,a.boss?9:5);if(a.boss)boss=null;if(!a.boss&&Math.random()<.10)spawnPowerItem(Math.random()<.7?'boost':'slow');audio.sfx(a.boss?70:210,a.boss?.45:.09,'sawtooth',a.boss?.11:.045)}
function reviveAtPortal(){if(config.players<2)return;ships.forEach(s=>{if(!s.alive){s.alive=true;s.hp=s.maxHp*.55;s.x=170;s.y=H*(s.slot===1?.44:.63);s.inv=2;s.speedMul=1;s.speedTimer=0;s.speedEffect='';toast(`${s.pilot} REVIVED BY THE RIFT`)}})}

function createPortal(){if(portal)return;portal={x:W+130,y:H*.5,r:92,phase:0};toast('MULTIDIMENSIONAL PORTAL AHEAD')}
function crossPortal(){portal=null;level++;dimIndex=(dimIndex+1)%dimensions.length;portalSegmentStart=distance;portalAt=distance+850;scrollSpeed=175+(level-1)*8.5;boss=null;bossSpawnedLevel=0;enemyShots=[];reviveAtPortal();ships.forEach(s=>{if(s.alive)s.hp=Math.min(s.maxHp,s.hp+s.maxHp*.12)});for(let i=0;i<55;i++)particle(W*.36,H*.5,dimensions[dimIndex].accent,8);toast(`LEVEL ${level} // ${dimensions[dimIndex].name} // THREAT RISING`);audio.sfx(92,.65,'sawtooth',.11)}

function update(dt,now){if(state!=='play'||paused)return;distance+=scrollSpeed*dt*.075;score+=Math.floor(scrollSpeed*dt*.018);spawnTimer-=dt;powerTimer-=dt;const diff=difficulty[config.difficulty],ls=levelScale(),spawnInterval=ls.spawn/diff.spawn;if(spawnTimer<=0){spawnAlien(false);if(level>=6&&Math.random()<.18)spawnAlien(false);if(level>=12&&Math.random()<.13)spawnAlien(false);spawnTimer=spawnInterval*(.72+Math.random()*.55)}if(powerTimer<=0){spawnPowerItem(Math.random()<.72?'boost':'slow');powerTimer=6.5+Math.random()*6}const progress=(distance-portalSegmentStart)/(portalAt-portalSegmentStart);if(level%3===0&&progress>.58&&bossSpawnedLevel!==level&&!boss)spawnAlien(true);if(distance>=portalAt-150&&!portal)createPortal();ships.forEach(s=>{if(s.alive)controls(s,dt,now)});
 for(const a of aliens){if(a.dead)continue;a.phase+=dt*(2.5+level*.04);const live=ships.filter(s=>s.alive),target=live.length?live[Math.floor(Math.random()*live.length)]:null;a.x-=(scrollSpeed*.17+a.speed)*dt;if(target){const dy=target.y-a.y;a.y+=Math.sign(dy)*Math.min(Math.abs(dy),a.speed*.33*dt);if(a.shoot&&a.x<W*.92)enemyFire(a,now);if(Math.hypot(a.x-target.x,a.y-target.y)<a.r+target.r){hurtShip(target,a.damage);a.x+=45}}}
 for(const b of shots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const a of aliens){if(a.dead)continue;if(Math.hypot(b.x-a.x,b.y-a.y)<b.r+a.r){a.hp-=b.damage;b.life=0;for(let i=0;i<4;i++)particle(b.x,b.y,b.color,2.6);if(a.hp<=0)killAlien(a);break}}}shots=shots.filter(b=>b.life>0&&b.x>-60&&b.x<W+100&&b.y>-80&&b.y<H+80);aliens=aliens.filter(a=>!a.dead&&a.x>-130);
 for(const b of enemyShots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const s of ships){if(!s.alive)continue;if(Math.hypot(b.x-s.x,b.y-s.y)<b.r+s.r){hurtShip(s,b.damage);b.life=0;break}}}enemyShots=enemyShots.filter(b=>b.life>0&&b.x>-100&&b.x<W+100&&b.y>-100&&b.y<H+100);
 for(const p of powerItems){p.phase+=dt*3.2;p.x-=scrollSpeed*.72*dt;p.life-=dt;for(const s of ships){if(!s.alive||p.life<=0)continue;if(Math.hypot(p.x-s.x,p.y-s.y)<p.r+s.r+5){applyPowerItem(s,p);p.life=0;break}}}powerItems=powerItems.filter(p=>p.life>0&&p.x>-80);
 if(portal){portal.phase+=dt*2.5;portal.x-=scrollSpeed*.62*dt;if(portal.x<W*.38)crossPortal()}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.965;p.vy*=.965;p.life-=dt});particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-28*dt);updateHUD()}
function endGame(){state='over';$('hud').classList.add('hidden');$('pauseBtn').classList.add('hidden');$('gameOver').classList.remove('hidden');$('finalDistance').textContent=Math.floor(distance)+'m';$('finalScore').textContent=score.toLocaleString();$('finalLevel').textContent=level;$('finalLine').textContent=`Reached ${dimensions[dimIndex].name} · ${kills} aliens eliminated.`}

function updateHUD(){const d=dimensions[dimIndex];$('dimensionName').textContent=d.name;$('dimensionName').style.color=d.accent;$('dimensionLevel').textContent='LEVEL '+String(level).padStart(2,'0');$('distance').textContent=String(Math.floor(distance)).padStart(4,'0')+'m';$('score').textContent=String(score).padStart(6,'0');$('kills').textContent=kills;const progress=Math.max(0,Math.min(1,(distance-portalSegmentStart)/(portalAt-portalSegmentStart)));$('portalProgress').style.width=(progress*100)+'%';$('portalProgress').style.background=`linear-gradient(90deg,${d.accent},#fff)`;const s1=ships[0];if(s1){$('p1Name').textContent=s1.pilot;$('p1hp').style.width=Math.max(0,s1.hp/s1.maxHp*100)+'%';$('p1hpText').textContent=Math.max(0,Math.ceil(s1.hp))}const s2=ships[1];$('p2Hud').classList.toggle('hidden',!s2);if(s2){$('p2Name').textContent=s2.pilot;$('p2hp').style.width=Math.max(0,s2.hp/s2.maxHp*100)+'%';$('p2hpText').textContent=Math.max(0,Math.ceil(s2.hp))}$('bossBar').classList.toggle('hidden',!boss||boss.dead);if(boss&&!boss.dead)$('bossHp').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%'}
function particle(x,y,color,power=4){const a=Math.random()*Math.PI*2,sp=(30+Math.random()*75)*power/4;particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.28+Math.random()*.65,max:.93,r:1+Math.random()*3,color})}

function drawBackground(){const d=dimensions[dimIndex],g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,d.bg1);g.addColorStop(1,d.bg2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const n of nebulae){const ng=ctx.createRadialGradient(n.x,n.y,0,n.x,n.y,n.r);ng.addColorStop(0,d.accent+'20');ng.addColorStop(1,'transparent');ctx.fillStyle=ng;ctx.fillRect(n.x-n.r,n.y-n.r,n.r*2,n.r*2);n.x-=state==='play'&&!paused?scrollSpeed*.008:0;if(n.x<-n.r)n.x=W+n.r}for(const s of stars){if(state==='play'&&!paused)s.x-=scrollSpeed*(.06+s.z*.2)*.016;if(s.x<0){s.x=W;s.y=Math.random()*H}ctx.globalAlpha=.25+s.z*.65;ctx.fillStyle=s.z>.75?d.accent:'#e8f2ff';ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.globalAlpha=1;ctx.strokeStyle=d.accent+'16';const off=(distance*2)%70;for(let x=-off;x<W;x+=70){ctx.beginPath();ctx.moveTo(x,H*.73);ctx.lineTo(x+180,H);ctx.stroke()}for(let y=H*.73;y<H;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function drawShip(s){if(!s.alive)return;ctx.save();ctx.translate(s.x,s.y);if(s.inv>0&&Math.floor(s.inv*14)%2===0)ctx.globalAlpha=.4;const trail=s.speedMul>1?80:s.speedMul<1?28:48,grad=ctx.createLinearGradient(-trail,0,0,0);grad.addColorStop(0,'transparent');grad.addColorStop(1,s.speedEffect==='SLOW'?'#fb7185':s.color);ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(-trail,-8);ctx.lineTo(-10,-4);ctx.lineTo(-10,4);ctx.lineTo(-trail,8);ctx.closePath();ctx.fill();ctx.shadowBlur=20;ctx.shadowColor=s.color;ctx.fillStyle='#dfeaff';ctx.beginPath();ctx.moveTo(28,0);ctx.lineTo(-11,-17);ctx.lineTo(-3,-5);ctx.lineTo(-25,-3);ctx.lineTo(-25,3);ctx.lineTo(-3,5);ctx.lineTo(-11,17);ctx.closePath();ctx.fill();ctx.fillStyle=s.color;ctx.beginPath();ctx.moveTo(17,0);ctx.lineTo(-5,-7);ctx.lineTo(-1,0);ctx.lineTo(-5,7);ctx.closePath();ctx.fill();ctx.restore();if(s.speedEffect){ctx.save();ctx.textAlign='center';ctx.font='700 10px Rajdhani';ctx.fillStyle=s.speedEffect==='BOOST'?'#34d399':'#fb7185';ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.fillText(`${s.speedEffect} ${Math.max(0,s.speedTimer).toFixed(1)}s`,s.x,s.y-31);ctx.restore()}}
function drawAlien(a){ctx.save();ctx.translate(a.x,a.y);ctx.shadowBlur=a.boss?28:16;ctx.shadowColor=a.color;ctx.fillStyle=a.color+'55';ctx.strokeStyle=a.color;ctx.lineWidth=a.boss?3:2;if(a.boss){ctx.rotate(Math.sin(a.phase)*.08);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.moveTo(22,0);ctx.lineTo(64,-8);ctx.lineTo(55,9);ctx.closePath();ctx.fill();ctx.stroke()}ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(9,-4,8,0,Math.PI*2);ctx.fill()}else if(a.name==='MANTA'){ctx.beginPath();ctx.moveTo(-26,0);ctx.quadraticCurveTo(0,-30,29,0);ctx.quadraticCurveTo(0,16,-26,0);ctx.fill();ctx.stroke()}else if(a.name==='EYE'){ctx.beginPath();ctx.arc(0,0,a.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(5,0,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(7,0,3,0,Math.PI*2);ctx.fill()}else if(a.name==='BRUTE'){ctx.rotate(a.phase*.15);ctx.beginPath();for(let i=0;i<8;i++){const an=i*Math.PI/4,r=i%2?a.r*.76:a.r;ctx.lineTo(Math.cos(an)*r,Math.sin(an)*r)}ctx.closePath();ctx.fill();ctx.stroke()}else{ctx.beginPath();for(let i=0;i<6;i++){const an=i*Math.PI/3;ctx.lineTo(Math.cos(an)*a.r,Math.sin(an)*a.r)}ctx.closePath();ctx.fill();ctx.stroke()}if(a.hp<a.maxHp){ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(-a.r,-a.r-10,a.r*2,3);ctx.fillStyle=a.color;ctx.fillRect(-a.r,-a.r-10,a.r*2*Math.max(0,a.hp/a.maxHp),3)}ctx.restore()}
function drawPowerItem(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.phase);ctx.shadowBlur=24;ctx.shadowColor=p.color;ctx.strokeStyle=p.color;ctx.fillStyle=p.color+'28';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-21);ctx.lineTo(21,0);ctx.lineTo(0,21);ctx.lineTo(-21,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate(-p.phase);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 17px Orbitron';ctx.fillText(p.type==='boost'?'↑':'↓',0,1);ctx.font='700 8px Rajdhani';ctx.fillStyle=p.color;ctx.fillText(p.type==='boost'?'BOOST':'SLOW',0,34);ctx.restore()}
function drawPortal(p){const d=dimensions[(dimIndex+1)%dimensions.length];ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.phase*.22);ctx.shadowBlur=30;ctx.shadowColor=d.accent;for(let i=0;i<5;i++){ctx.strokeStyle=i%2?d.accent:'#fff';ctx.globalAlpha=.18+i*.12;ctx.lineWidth=2+i*.7;ctx.beginPath();ctx.arc(0,0,p.r-i*12,p.phase+i*.6,p.phase+Math.PI*1.55+i*.6);ctx.stroke()}ctx.globalAlpha=1;const g=ctx.createRadialGradient(0,0,4,0,0,p.r*.7);g.addColorStop(0,'#ffffffdd');g.addColorStop(.2,d.accent+'bb');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,p.r*.7,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.textAlign='center';ctx.fillStyle=d.accent;ctx.font='700 10px Orbitron';ctx.fillText(`NEXT // ${d.name}`,p.x,p.y+p.r+28);ctx.restore()}
function drawShots(){for(const b of shots){ctx.save();ctx.shadowBlur=12;ctx.shadowColor=b.color;ctx.strokeStyle=b.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x-b.vx*.018,b.y-b.vy*.018);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}for(const b of enemyShots){ctx.save();ctx.shadowBlur=13;ctx.shadowColor=b.color;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawParticles(){for(const p of particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.shadowBlur=8;ctx.shadowColor=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawThreatBadge(){if(state!=='play')return;const ls=levelScale();ctx.save();ctx.textAlign='right';ctx.font='700 10px Rajdhani';ctx.fillStyle='rgba(220,235,255,.7)';ctx.fillText(`THREAT LV.${level} · ENEMY HP ×${ls.hp.toFixed(2)} · SPAWN ${ls.spawn.toFixed(2)}s`,W-24,H-25);ctx.restore()}
function draw(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBackground();if(state==='play'||state==='over'){for(const p of powerItems)drawPowerItem(p);for(const a of aliens)drawAlien(a);drawShots();ships.forEach(drawShip);if(portal)drawPortal(portal);drawParticles();drawThreatBadge()}ctx.restore()}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;update(dt,now);draw();requestAnimationFrame(loop)}
requestAnimationFrame(loop);